name: composite

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  composite:
      runs-on: ubuntu-latest

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      steps:
          - uses: ./.github/workflows/blank.yml
          - uses: paras-31/test-reusable-g-action/.github/workflows/blank.yml@main
      
